### ISSUE TITLE
improve navbar and footer 

### ISSUE THREAD

**Issue by kratik1237** [Muhammad-Owais-Warsi/NPM-Suggester#29]
**Please describe.**

**Describe the solution you'd like**

- [x] VSoC Contributor. 

**Email**
Please write your email ID. If VSoC Contributor.

**Comment by kratik1237** [comment]
please assign the issue #29 @Muhammad-Owais-Warsi

**Comment by Muhammad-Owais-Warsi** [comment]
Please drop your email

**Comment by kratik1237** [comment]
Email- kratikkhatri7287@gmail.com

**Comment by kratik1237** [comment]
@Muhammad-Owais-Warsi yes
