### ISSUE TITLE
Revamp of about and contact page

### ISSUE THREAD

**Issue by kom-senapati** [Muhammad-Owais-Warsi/NPM-Suggester#37]
**Please describe.**
The gradient doesn't look good for the About and Contact page.

**Describe the solution you'd like**
White background and gradient or black text.

- [X] VSoC Contributor. 

**Email**
komnoob123@gmail.com

**Comment by Muhammad-Owais-Warsi** [comment]
@Mehak-Mattoo is working on enhancing these two pages , ones she raised the pr , you can  change the design of required, or else you both can discuss on discord , I'll assign it accordingly
