### ISSUE TITLE
resolved feed back form bug and added footer

### ISSUE THREAD

**Issue by Krishna100604** [Muhammad-Owais-Warsi/NPM-Suggester#42]
![Screenshot (214)](https://github.com/Muhammad-Owais-Warsi/NPM-Suggester/assets/110299021/5e5b8dcd-7cca-47ab-a7fd-6b00f1d95c66)

*** this was the bug

![Screenshot (216)](https://github.com/Muhammad-Owais-Warsi/NPM-Suggester/assets/110299021/f41e0812-98dc-41b0-8db0-d9244051029e)
![Screenshot (215)](https://github.com/Muhammad-Owais-Warsi/NPM-Suggester/assets/110299021/07f686f2-3bf0-4a23-a432-ca4959abd56b)

***enhanced

@Muhammad-Owais-Warsi  assign me this

**Comment by Muhammad-Owais-Warsi** [comment]
@Krishna100604 as I have no plan to add backend in this app, so this form is of no use . Instead we can use some feedback form services suitable for react

**Comment by Krishna100604** [comment]
> @Krishna100604 as I have no plan to add backend in this app, so this form is of no use . Instead we can use some feedback form services suitable for react

so i just remove the form
