### ISSUE TITLE
added contact and about pages

### ISSUE THREAD

**Issue by Krishna100604** [Muhammad-Owais-Warsi/NPM-Suggester#6]
https://github.com/Muhammad-Owais-Warsi/NPM-Suggester/assets/110299021/2343f3cf-b80f-4e33-a3c6-b7bfea2551fb

@Muhammad-Owais-Warsi  assign me this

**Comment by Muhammad-Owais-Warsi** [comment]
@Krishna100604 i think these big pages are not required. For contact you can just add my GitHub profile link or just attach my mail. For about section also we can do some similar stuff. 

- The Home page is looking good . Just remove the ```Why use NPM section```
- Their is an unnecessary scrollbar plz remove that , and make sure everything is till responsive in nature.
